# -*- coding: utf-8 -*-
"""example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmBw5eqL6fRHAUouEeJUbvUzSAI-3kky
"""

import numpy as np

# Example input values
t = 66367               # Time passed since measuring v0 at r0 in seconds
r0 = 13926800           # Initial CME distance from the Sun (in km)
v0 = 800                # Initial CME speed at r0 (in km/s)
r_at_t = 59999765       # Measured CME distance at time t (in km)
v_at_t = 619            # Measured CME speed at time t (in km/s)

# Call the estimation function
w_est, gamma_est = get_w_gamma_estimates(
    t=t,
    r0=r0,
    v0=v0,
    r_at_t=r_at_t,
    v_at_t=v_at_t
)

# Print the results
print("---- CME Drag-Based Parameter Estimates ----")
print(f"Estimated Solar Wind Speed: {w_est:.2f} km/s")
print(f"Estimated Drag Parameter: {gamma_est:.2e} 1/km")